language: android
sudo: true
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")

before_install:
  - rm -fr $HOME/android-ndk-r14b
  - curl -L http://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -O
  - unzip -oq android-ndk-r14b-linux-x86_64.zip
  - rm android-ndk-r14b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r14b